config/routes.rb
Ticketee::Application.routes.draw do

  devise_for :users, :controllers=> { :registrations => "registrations" }
	get '/awaiting_confirmation',		:to=>"users#confirmation",		:as=>'confirm_user'
  resources :projects do 
		resources :tickets
	end
	resources :tickets do
		resources :comments
	end
	namespace :admin do
		root :to => "base#index"
		resources :users do 
			resources :permissions
		end
		resources :states do
			member do
				get :make_default
			end
		end
	end
	resources :files
	put '/admin/users/:user_id/permissions',
				:to=>'admin/permissions#update',
				:as=>:update_user_permissions
	root :to => "projects#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
	<%  if content_for?(:title) %>
	  <%=  yield(:title) %>
	<%  else %>
	  Ticketee
	<%  end %>
  </title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <style>
	<%  for state in @states %>
	.state_<%=state.name.parameterize%> {
	  background: <%=  state.background %>;
	  color: <%=  state.color %>;
	}
	<%  end %>
  </style>  
  <%= csrf_meta_tags %>
</head>
<body>
<%  flash.each do |key,value| %>
<div class='flash' id='<%=key%>'>
  <%= value %>
</div>
<% end %>
<h1><%=  link_to "Ticketee", root_path %></h1>  
<nav>
  <%=  admins_only do %>
  <%=  link_to "Admin", admin_root_path %><br>
  <%  end %>
  <% if user_signed_in? %>
	Signed in as <%=  current_user.email %>
	<%= link_to "Sign out", destroy_user_session_path, :method =>:delete %>
  <% else %>
	<%=  link_to "Sign up", new_user_registration_path %>
  <% end %>
	<%=  link_to "Sign in" ,new_user_session_path %>
</nav>
<%= yield %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>